import { assert, it } from "@effect/vitest";
import * as NodeServices from "@effect/platform-node/NodeServices";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import { saveCodexGeneratedImage } from "./CodexGeneratedImage.ts";

it.effect("saves generated bytes at a repeatable path and returns a compact image reference", () =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const dir = yield* fs.makeTempDirectoryScoped();
    const item = {
      id: "image-1",
      status: "completed",
      result: Buffer.from("image bytes").toString("base64"),
    };
    const first = yield* saveCodexGeneratedImage(fs, dir, "thread-1", item);
    assert.equal(yield* saveCodexGeneratedImage(fs, dir, "thread-1", item), first);
    const files = yield* fs.readDirectory(dir);
    assert.lengthOf(files, 1);
    assert.equal(yield* fs.readFileString(`${dir}/${files[0]}`), "image bytes");
    assert.include(first!, "![Generated image]");
    assert.notInclude(first!, item.result);
    assert.isNull(
      yield* saveCodexGeneratedImage(fs, dir, "thread-1", { ...item, status: "in_progress" }),
    );
    assert.equal(
      yield* saveCodexGeneratedImage(fs, dir, "thread-1", {
        ...item,
        savedPath: "/tmp/my image.png",
      }),
      "![Generated image](</tmp/my%20image.png>)",
    );
  }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)),
);
